server:
  port: 8762
  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: member

  #数据库连接信息
  datasource:
    name: shopdb
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&useSSL=true
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual
#        concurrency: 1
#        max-concurrency: 1
#        prefetch: 1
#        auto-startup: true
#    virtual-host: /
#    template:
#      mandatory: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sym.shopping.base.entity
